#!/usr/bin/env bash

# Wait for system to catch up.
sleep 10s

# start timechief
cd /opt/timechief-launcher/bin
/opt/timechief-launcher/bin/timechief-launcher run-client 2>&1 | multilog T s10485760 n10 /opt/timechief-launcher/logs/timechief-launcher
