#!/bin/bash
set -e
WORK_DIR=$1
LOG_FILE=$2

if [ -z "$WORK_DIR" ] || [ -z "$LOG_FILE" ] ; then
  echo "Usage: $0 <work-dir> <log-file>"
  exit 1
fi

cd $WORK_DIR
./timechief-client-electron . 2>&1 >> $LOG_FILE