#!/bin/bash
set -e
set -x

# This script is to configure raspberry pi to join a wifi network.

SSID=$1
PASSWORD=$2
IFNAME=$3

if [ -z "$SSID" ]; then
    echo "SSID is required"
    exit 1
fi

if [ -z "$PASSWORD" ]; then
    echo "PASSWORD is required"
    exit 1
fi

if [ -z "$IFNAME" ]; then
    echo "IFNAME is required"
    exit 1
fi

# Disable dnsmasq, if it is running.
sudo systemctl stop dnsmasq || true

# Disable hostapd, if it is running.
sudo systemctl stop hostapd || true

# Bring down the interface.
sudo ip addr flush dev $IFNAME
sudo ip link set $IFNAME down

# Bring up the interface.
sudo ip link set $IFNAME up

# Now connect.
sudo wpa_passphrase $SSID $PASSWORD > /tmp/wpa_supplicant.conf
sudo wpa_supplicant -B -i $IFNAME -c /tmp/wpa_supplicant.conf

# Now start dhcpcd.
sudo systemctl start dhcpcd