#!/bin/bash
set -e

SSID=$1
PASSWORD=$2
IFNAME=$3
# AP_IP is IP address in form 192.168.0.1/24.
AP_IP=$4
DHCP_RANGE=$5

if [ -z "$SSID" ]; then
    echo "SSID is required"
    exit 1
fi

if [ -z "$PASSWORD" ]; then
    echo "PASSWORD is required"
    exit 1
fi

if [ -z "$IFNAME" ]; then
    echo "IFNAME is required"
    exit 1
fi

if [ -z "$AP_IP" ]; then
    echo "AP_IP is required"
    exit 1
fi

if [ -z "$DHCP_RANGE" ]; then
    echo "DHCP_RANGE is required"
    exit 1
fi

# This script is to configure a wifi hotspot on raspberry pi.

# Disable dhcpcd on the interface.
sudo systemctl stop dhcpcd

# Create dnsmasq config file.
sudo cat > /tmp/dnsmasq.conf <<EOF
interface=$IFNAME
dhcp-range=$DHCP_RANGE
EOF

# Create hostapd config file.
sudo cat > /tmp/hostapd.conf <<EOF
interface=$IFNAME
driver=nl80211
ssid=$SSID
hw_mode=g
channel=6
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=$PASSWORD
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
EOF

# Disable wpa_supplicant on the interface.
sudo wpa_cli -i $IFNAME terminate

# Configure the interface.
sudo ip addr flush dev $IFNAME
sudo ip link set $IFNAME down
sudo ip link set $IFNAME up
sudo ip addr add $AP_IP dev $IFNAME

# Start dnsmasq with systemd.
sudo systemctl start dnsmasq

# Start hostapd with systemd.
sudo systemctl start hostapd


