#!/usr/bin/python
import sys
import subprocess
import json
import re

ifname = sys.argv[1]

cmd = ['sudo', 'iwlist', ifname, 'scan']

try:
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT).decode('utf-8')
except subprocess.CalledProcessError as e:
    print(e.output.decode('utf-8'))
    sys.exit(1)

networks = []

network = {}
cell_re = 'Cell \d+ - '
essid_re = 'ESSID:"(\S+)"'
quality_re = 'Quality=(\d+\/\d+)'
for line in output.split('\n'):
    line = line.strip()
    
    if re.search(cell_re, line):
        network = {}
        networks.append(network)
    if re.search(essid_re, line):
        ssid = re.search(essid_re, line).group(1)
        network['SSID'] = ssid
    elif re.search(quality_re, line):
        quality = re.search(quality_re, line).group(1)
        network['Signal'] = quality
    elif line.startswith('IE: IEEE 802.11i/WPA2'):
        network['Security'] = 'WPA2'

print(json.dumps(networks, indent=4))