package layout

import v2 "github.com/johnny-morrice/timechief-client/launcher/launcher/client/timechief/v2"

func GetConfigurations() []Configuration {
	return []Configuration{
		{
			MinWidth:  -1,
			MaxWidth:  799,
			MinHeight: -1,
			MaxHeight: 479,
			Layout:    DefaultSmallLayout(),
		},
		{
			MinWidth:  800,
			MaxWidth:  -1,
			MinHeight: 480,
			MaxHeight: 1023,
			Layout:    DefaultSevenInchLayout(),
		},
		{
			MinWidth:  800,
			MaxWidth:  1023,
			MinHeight: 1024,
			MaxHeight: -1,
			Layout:    DefaultPlannerLayout(),
		},
		{
			MinWidth:  1024,
			MaxWidth:  -1,
			MinHeight: 720,
			MaxHeight: -1,
			Layout:    DefaultTouch2Layout(),
		},
	}
}

const fgColor = "#008000ff"
const bgColor = "#000000ff"
const errorColor = "#ffa500ff"
const borderRadius = "0px"
const timeFont = "Seven Segment"
const mainFont = "'Titillium Web'"
const borderWidth = "2px"

func DefaultSevenInchLayout() v2.Theme {
	return v2.Theme{
		ForegroundColor: fgColor,
		BackgroundColor: bgColor,

		BoxBackgroundColor: bgColor,
		BoxBorderRadius:    borderRadius,
		BoxBorderWidth:     borderWidth,
		BoxBorderColor:     fgColor,

		MainFont:  mainFont,
		TimeFont:  timeFont,
		TimeColor: fgColor,

		ButtonBorderRadius:    borderRadius,
		ButtonBorderWidth:     borderWidth,
		ButtonBorderColor:     fgColor,
		ButtonForegroundColor: fgColor,
		ButtonBackgroundColor: bgColor,

		DisabledButtonBorderColor:     errorColor,
		DisabledButtonForegroundColor: errorColor,
		DisabledButtonBackgroundColor: bgColor,

		ErrorColor: errorColor,

		ImageFit: "none",

		LayoutType:           "seven_inch",
		DisplayWidth:         800,
		DisplayHeight:        480,
		WidgetSwitcherX:      "20px",
		WidgetSwitcherY:      "20px",
		WidgetSwitcherWidth:  "260px",
		WidgetSwitcherHeight: "380px",
		DateTimeX:            "340px",
		DateTimeY:            "20px",
		DateTimeWidth:        "440px",
		DateTimeHeight:       "210px",
		ActionCenterX:        "350px",
		ActionCenterY:        "260px",
		ActionCenterWidth:    "380px",
		ActionCenterHeight:   "140px",
		PlannerX:             "20px",
		PlannerY:             "480px",
		PlannerWidth:         "440px",
		PlannerHeight:        "800px",

		BodyFontSize:                       "16pt",
		DateFontSize:                       "36pt",
		TimeFontSize:                       "102pt",
		CurrentWeatherFontSize:             "18pt",
		ActionButtonFontSize:               "18pt",
		SwitcherButtonFontSize:             "16pt",
		AstroFontSize:                      "16pt",
		WeatherDataFontSize:                "32pt",
		CurrentWeatherIconFontSize:         "28pt",
		ForecastIconFontSize:               "32pt",
		ForecastWeatherTableIconFontSize:   "24pt",
		ForecastControlButtonFontSize:      "16pt",
		ForecastControlLabelFontSize:       "16pt",
		CalendarDayDateFontSize:            "20pt",
		CalendarDayFontSize:                "14pt",
		EventCalendarControlButtonFontSize: "16pt",
		FortuneMessageFontSize:             "14pt",
		NextEventTimeFontSize:              "18pt",
		NextEventTextFontSize:              "16pt",
		LoadingGridFontSize:                "16pt",
		FortuneMascotHeight:                "120px",
		EventMascotHeight:                  "100px",
		MascotType:                         "dark",
		StatusNoteFontSize:                 "16pt",

		PlannerDayEventCount: 0,
	}
}

func DefaultTouch2Layout() v2.Theme {
	return v2.Theme{
		ForegroundColor: fgColor,
		BackgroundColor: bgColor,

		BoxBackgroundColor: bgColor,
		BoxBorderRadius:    borderRadius,
		BoxBorderWidth:     borderWidth,
		BoxBorderColor:     fgColor,

		MainFont:  mainFont,
		TimeFont:  timeFont,
		TimeColor: fgColor,

		ButtonBorderRadius:    borderRadius,
		ButtonBorderWidth:     borderWidth,
		ButtonBorderColor:     fgColor,
		ButtonForegroundColor: fgColor,
		ButtonBackgroundColor: bgColor,

		DisabledButtonBorderColor:     errorColor,
		DisabledButtonForegroundColor: errorColor,
		DisabledButtonBackgroundColor: bgColor,

		ErrorColor: errorColor,

		ImageFit: "none",

		LayoutType:           "seven_inch",
		DisplayWidth:         800,
		DisplayHeight:        480,
		WidgetSwitcherX:      "32px",
		WidgetSwitcherY:      "30px",
		WidgetSwitcherWidth:  "416px",
		WidgetSwitcherHeight: "570px",
		DateTimeX:            "544px",
		DateTimeY:            "30px",
		DateTimeWidth:        "704px",
		DateTimeHeight:       "315px",
		ActionCenterX:        "560px",
		ActionCenterY:        "390px",
		ActionCenterWidth:    "608px",
		ActionCenterHeight:   "210px",
		PlannerX:             "32px",
		PlannerY:             "720px",
		PlannerWidth:         "704px",
		PlannerHeight:        "1200px",

		BodyFontSize:                       "28pt",
		DateFontSize:                       "48pt",
		TimeFontSize:                       "136pt",
		CurrentWeatherFontSize:             "32pt",
		ActionButtonFontSize:               "28pt",
		SwitcherButtonFontSize:             "28pt",
		AstroFontSize:                      "26pt",
		WeatherDataFontSize:                "42pt",
		CurrentWeatherIconFontSize:         "42pt",
		ForecastIconFontSize:               "42pt",
		ForecastWeatherTableIconFontSize:   "32pt",
		ForecastControlButtonFontSize:      "28pt",
		ForecastControlLabelFontSize:       "28pt",
		CalendarDayDateFontSize:            "26pt",
		CalendarDayFontSize:                "18pt",
		EventCalendarControlButtonFontSize: "28pt",
		FortuneMessageFontSize:             "24pt",
		NextEventTimeFontSize:              "24pt",
		NextEventTextFontSize:              "28pt",
		LoadingGridFontSize:                "28pt",
		FortuneMascotHeight:                "180px",
		EventMascotHeight:                  "150px",
		MascotType:                         "dark",
		StatusNoteFontSize:                 "28pt",
		PlannerDateCellFontSize:            "16pt",
		PlannerDateCellWidth:               "112px",
		PlannerDateCellHeight:              "75px",
		PlannerDayEventCount:               0,
	}
}

func DefaultSmallLayout() v2.Theme {
	return v2.Theme{
		ForegroundColor: fgColor,
		BackgroundColor: bgColor,

		BoxBackgroundColor: bgColor,
		BoxBorderRadius:    borderRadius,
		BoxBorderWidth:     borderWidth,
		BoxBorderColor:     fgColor,

		MainFont:  mainFont,
		TimeFont:  timeFont,
		TimeColor: fgColor,

		ButtonBorderRadius:    borderRadius,
		ButtonBorderWidth:     borderWidth,
		ButtonBorderColor:     fgColor,
		ButtonForegroundColor: fgColor,
		ButtonBackgroundColor: bgColor,

		DisabledButtonBorderColor:     errorColor,
		DisabledButtonForegroundColor: errorColor,
		DisabledButtonBackgroundColor: bgColor,

		ErrorColor: errorColor,

		LayoutType:                         "small",
		DisplayWidth:                       480,
		DisplayHeight:                      320,
		WidgetSwitcherX:                    "20px",
		WidgetSwitcherY:                    "20px",
		WidgetSwitcherWidth:                "140px",
		WidgetSwitcherHeight:               "80px",
		DateTimeX:                          "150px",
		DateTimeY:                          "20px",
		DateTimeWidth:                      "200px",
		DateTimeHeight:                     "80px",
		ActionCenterX:                      "20px",
		ActionCenterY:                      "100px",
		ActionCenterWidth:                  "400px",
		ActionCenterHeight:                 "100px",
		PlannerX:                           "20px",
		PlannerY:                           "440px",
		PlannerWidth:                       "710px",
		PlannerHeight:                      "800px",
		BodyFontSize:                       "14pt",
		DateFontSize:                       "8pt",
		TimeFontSize:                       "32pt",
		CurrentWeatherFontSize:             "14pt",
		ActionButtonFontSize:               "14pt",
		SwitcherButtonFontSize:             "14pt",
		AstroFontSize:                      "14pt",
		WeatherDataFontSize:                "14pt",
		CurrentWeatherIconFontSize:         "14pt",
		ForecastIconFontSize:               "14pt",
		ForecastWeatherTableIconFontSize:   "14pt",
		ForecastControlButtonFontSize:      "16pt",
		ForecastControlLabelFontSize:       "16pt",
		CalendarDayDateFontSize:            "20pt",
		CalendarDayFontSize:                "14pt",
		EventCalendarControlButtonFontSize: "14pt",
		FortuneMessageFontSize:             "8pt",
		NextEventTimeFontSize:              "8pt",
		NextEventTextFontSize:              "8pt",
		LoadingGridFontSize:                "14pt",
		PlannerDateCellFontSize:            "8pt",
		PlannerDateCellWidth:               "70px",
		PlannerDateCellHeight:              "50px",
		PlannerDayEventCount:               0,
		FortuneMascotHeight:                "50px",
		EventMascotHeight:                  "50px",
		StatusNoteFontSize:                 "8pt",
	}
}

func DefaultPlannerLayout() v2.Theme {
	return v2.Theme{
		ForegroundColor: fgColor,
		BackgroundColor: bgColor,

		BoxBackgroundColor: bgColor,
		BoxBorderRadius:    borderRadius,
		BoxBorderWidth:     borderWidth,
		BoxBorderColor:     fgColor,

		MainFont:  mainFont,
		TimeFont:  timeFont,
		TimeColor: fgColor,

		ButtonBorderRadius:    borderRadius,
		ButtonBorderWidth:     borderWidth,
		ButtonBorderColor:     fgColor,
		ButtonForegroundColor: fgColor,
		ButtonBackgroundColor: bgColor,

		DisabledButtonBorderColor:     errorColor,
		DisabledButtonForegroundColor: errorColor,
		DisabledButtonBackgroundColor: bgColor,

		ErrorColor:                         errorColor,
		DisplayWidth:                       800,
		DisplayHeight:                      1024,
		LayoutType:                         "planner",
		WidgetSwitcherX:                    "20px",
		WidgetSwitcherY:                    "20px",
		WidgetSwitcherWidth:                "260px",
		WidgetSwitcherHeight:               "380px",
		DateTimeX:                          "340px",
		DateTimeY:                          "20px",
		DateTimeWidth:                      "440px",
		DateTimeHeight:                     "200px",
		ActionCenterX:                      "350px",
		ActionCenterY:                      "260px",
		ActionCenterWidth:                  "380px",
		ActionCenterHeight:                 "140px",
		PlannerX:                           "20px",
		PlannerY:                           "480px",
		PlannerWidth:                       "760px",
		PlannerHeight:                      "400px",
		BodyFontSize:                       "16pt",
		DateFontSize:                       "36pt",
		TimeFontSize:                       "98pt",
		CurrentWeatherFontSize:             "18pt",
		ActionButtonFontSize:               "18pt",
		SwitcherButtonFontSize:             "16pt",
		AstroFontSize:                      "16pt",
		WeatherDataFontSize:                "32pt",
		CurrentWeatherIconFontSize:         "28pt",
		ForecastIconFontSize:               "32pt",
		ForecastWeatherTableIconFontSize:   "24pt",
		ForecastControlButtonFontSize:      "16pt",
		ForecastControlLabelFontSize:       "16pt",
		CalendarDayDateFontSize:            "20pt",
		CalendarDayFontSize:                "14pt",
		EventCalendarControlButtonFontSize: "16pt",
		FortuneMessageFontSize:             "14pt",
		NextEventTimeFontSize:              "18pt",
		NextEventTextFontSize:              "16pt",
		LoadingGridFontSize:                "16pt",
		PlannerDateCellFontSize:            "6pt",
		PlannerDateCellWidth:               "50px",
		PlannerDateCellHeight:              "20px",
		PlannerDayEventCount:               0,
		FortuneMascotHeight:                "120px",
		EventMascotHeight:                  "100px",
		StatusNoteFontSize:                 "14pt",
	}
}
